/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package frames;

import clases.Seguridad;
import clases.Sesion;
import java.awt.Color;
import java.awt.Image;
import javax.swing.JOptionPane;
import paquete.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author ayele
 */
public class Login extends javax.swing.JFrame {
     private final Conexion conexion;
   

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
          conexion= new Conexion(); // usamos tu clase
          this.setLocationRelativeTo(null); // Pantalla centrada 
        this.setTitle("Login - Abarrotes 'La Gloria'");
        ImageIcon icono=new ImageIcon(getClass().getResource("/imagenes/fondoAba.jpg"));
        Image imagenEscalada=icono.getImage().getScaledInstance(1536, 861, Image.SCALE_SMOOTH);
        ImageIcon iconoFinal = new ImageIcon(imagenEscalada);
        lblFondo.setIcon(iconoFinal);
        panel.setBackground(new Color(237, 198, 142, 128)); // #edc68e con 50% de opacidad
        panel.setOpaque(true); // ¡necesario si quieres que se vea la transparencia!
        ImageIcon logo=new ImageIcon(getClass().getResource("/imagenes/Logo AbeGloria.png"));
        Image logoEscalado=logo.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        ImageIcon logoFinal= new ImageIcon(logoEscalado);
        lblLogo.setIcon(logoFinal);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        txtUsu = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        passContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnOlvide = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(237, 198, 142));

        txtUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel16.setText("Usuario");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Login");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnIngresar.setBackground(new java.awt.Color(235, 231, 167));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarbtnIngresarActionPerformed(evt);
            }
        });

        btnOlvide.setBackground(new java.awt.Color(235, 231, 167));
        btnOlvide.setText("Olvidé la contraseña");
        btnOlvide.setBorder(null);
        btnOlvide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidebtnOlvideActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel18.setText("Contraseña ");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnOlvide, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                .addComponent(passContraseña, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOlvide, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 289, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblFondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 332, Short.MAX_VALUE)
                    .addComponent(lblFondo)
                    .addGap(0, 333, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuActionPerformed

    private void btnIngresarbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarbtnIngresarActionPerformed
        // TODO add your handling code here:
        // Obtener valores de los campos
    String usuario = txtUsu.getText().trim();
    String password = new String(passContraseña.getPassword()).trim();

    // Validar campos vacíos
    if (usuario.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ El usuario o la contraseña están vacíos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    

    if (conexion == null) {
        JOptionPane.showMessageDialog(this, "❌ No se pudo conectar con la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Hashear la contraseña antes de comparar
        String passwordHasheada = Seguridad.hashearSHA256(password);

        // Campos y valores a buscar (usuario activo con contraseña válida)
        String[] campos = {"nombre_usuario", "contraseña", "estado"};
        Object[] valores = {usuario, passwordHasheada, 1};

        // Ejecutar búsqueda con tu método personalizado
        ResultSet rs = conexion.buscarPorCampos("usuario", campos, valores);

        if (rs != null && rs.next()) {
            // Obtener datos del usuario encontrado
            int idUsuario = rs.getInt("id_usuario");
            int idRol = rs.getInt("id_rol");
            String nombreUsuario = rs.getString("nombre_usuario");

            // Guardar sesión
            Sesion.setIdUsuario(idUsuario);
            Sesion.setRol(idRol);
            Sesion.setNombreUsuario(nombreUsuario);

            // Mostrar mensaje y redirigir según el rol
            if (idRol == 1) { // Si el rol es administrador
                JOptionPane.showMessageDialog(this, "✅ Bienvenido Administrador " + nombreUsuario);
                new InicioAdmin().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "✅ Bienvenido " + nombreUsuario);
                new InicioGene().setVisible(true);
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(this, "❌ Usuario o contraseña incorrectos, o el usuario está inactivo.", "Error de inicio de sesión", JOptionPane.ERROR_MESSAGE);
        }


    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "❌ Error al consultar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnIngresarbtnIngresarActionPerformed

    
    private void btnOlvidebtnOlvideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidebtnOlvideActionPerformed
        // TODO add your handling code here:
        new RecuContra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOlvidebtnOlvideActionPerformed

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnOlvide;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField passContraseña;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
